package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class tb1 {
    public static final int[] a = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.reddit.secondpage.R.attr.backgroundTint, com.reddit.secondpage.R.attr.behavior_autoExpandOnRequestChildRectangleOffscreen, com.reddit.secondpage.R.attr.behavior_draggable, com.reddit.secondpage.R.attr.behavior_draggableOnNestedScroll, com.reddit.secondpage.R.attr.behavior_expandedOffset, com.reddit.secondpage.R.attr.behavior_fitToContents, com.reddit.secondpage.R.attr.behavior_halfExpandedRatio, com.reddit.secondpage.R.attr.behavior_hideable, com.reddit.secondpage.R.attr.behavior_multipleScrollingChildrenSupported, com.reddit.secondpage.R.attr.behavior_peekHeight, com.reddit.secondpage.R.attr.behavior_saveFlags, com.reddit.secondpage.R.attr.behavior_significantVelocityThreshold, com.reddit.secondpage.R.attr.behavior_skipCollapsed, com.reddit.secondpage.R.attr.gestureInsetBottomIgnored, com.reddit.secondpage.R.attr.marginLeftSystemWindowInsets, com.reddit.secondpage.R.attr.marginRightSystemWindowInsets, com.reddit.secondpage.R.attr.marginTopSystemWindowInsets, com.reddit.secondpage.R.attr.paddingBottomSystemWindowInsets, com.reddit.secondpage.R.attr.paddingLeftSystemWindowInsets, com.reddit.secondpage.R.attr.paddingRightSystemWindowInsets, com.reddit.secondpage.R.attr.paddingTopSystemWindowInsets, com.reddit.secondpage.R.attr.shapeAppearance, com.reddit.secondpage.R.attr.shapeAppearanceOverlay, com.reddit.secondpage.R.attr.shouldRemoveExpandedCorners};
    public static final int[] b = {com.reddit.secondpage.R.attr.carousel_alignment, com.reddit.secondpage.R.attr.carousel_backwardTransition, com.reddit.secondpage.R.attr.carousel_emptyViewsBehavior, com.reddit.secondpage.R.attr.carousel_firstView, com.reddit.secondpage.R.attr.carousel_forwardTransition, com.reddit.secondpage.R.attr.carousel_infinite, com.reddit.secondpage.R.attr.carousel_nextState, com.reddit.secondpage.R.attr.carousel_previousState, com.reddit.secondpage.R.attr.carousel_touchUpMode, com.reddit.secondpage.R.attr.carousel_touchUp_dampeningFactor, com.reddit.secondpage.R.attr.carousel_touchUp_velocityThreshold};
    public static final int[] c = {com.reddit.secondpage.R.attr.behavior_autoHide, com.reddit.secondpage.R.attr.behavior_autoShrink};
    public static final int[] d = {com.reddit.secondpage.R.attr.behavior_autoHide};
    public static final int[] e = {com.reddit.secondpage.R.attr.focusRingsEnabled, com.reddit.secondpage.R.attr.focusRingsInnerStrokeColor, com.reddit.secondpage.R.attr.focusRingsInnerStrokeInset, com.reddit.secondpage.R.attr.focusRingsInnerStrokeWidth, com.reddit.secondpage.R.attr.focusRingsInset, com.reddit.secondpage.R.attr.focusRingsOuterStrokeColor, com.reddit.secondpage.R.attr.focusRingsOuterStrokeWidth, com.reddit.secondpage.R.attr.focusRingsRadius, com.reddit.secondpage.R.attr.focusRingsShapeAppearance};
    public static final int[] f = {com.reddit.secondpage.R.attr.shapeAppearance, com.reddit.secondpage.R.attr.shapeAppearanceOverlay};
    public static final int[] g = {com.reddit.secondpage.R.attr.behavior_overlapTop};
    public static final int[] h = {com.reddit.secondpage.R.attr.cornerFamily, com.reddit.secondpage.R.attr.cornerFamilyBottomLeft, com.reddit.secondpage.R.attr.cornerFamilyBottomRight, com.reddit.secondpage.R.attr.cornerFamilyTopLeft, com.reddit.secondpage.R.attr.cornerFamilyTopRight, com.reddit.secondpage.R.attr.cornerSize, com.reddit.secondpage.R.attr.cornerSizeBottomLeft, com.reddit.secondpage.R.attr.cornerSizeBottomRight, com.reddit.secondpage.R.attr.cornerSizeTopLeft, com.reddit.secondpage.R.attr.cornerSizeTopRight};
    public static final int[] i = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.reddit.secondpage.R.attr.backgroundTint, com.reddit.secondpage.R.attr.behavior_draggable, com.reddit.secondpage.R.attr.coplanarSiblingViewId, com.reddit.secondpage.R.attr.shapeAppearance, com.reddit.secondpage.R.attr.shapeAppearanceOverlay};
}
