package defpackage;

/* JADX INFO: compiled from: r8-map-id-7d02091066cdaef854dd62631b7ece0560bf3f98008d2b2dd5cfb5f5ba2a990d */
/* JADX INFO: loaded from: classes.dex */
public abstract class u22 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final aa0 D;
    public static final zb0 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final aa0 I;
    public static final zb0 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final aa0 N;
    public static final zb0 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final aa0 S;
    public static final zb0 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final aa0 X;
    public static final zb0 Y;
    public static final long Z;
    public static final zb0 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final aa0 c0;
    public static final long d;
    public static final zb0 d0;
    public static final aa0 e;
    public static final long e0;
    public static final zb0 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final aa0 h0;
    public static final long i;
    public static final zb0 i0;
    public static final aa0 j;
    public static final long j0;
    public static final zb0 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final aa0 m0;
    public static final long n;
    public static final zb0 n0;
    public static final aa0 o;
    public static final long o0;
    public static final zb0 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final aa0 r0;
    public static final long s;
    public static final zb0 s0;
    public static final aa0 t;
    public static final long t0;
    public static final zb0 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final aa0 w0;
    public static final long x;
    public static final aa0 y;
    public static final zb0 z;

    static {
        aa0 aa0Var = e32.a;
        zb0 zb0Var = lv1.b;
        a = zb0Var;
        b = uc1.o(24.0d);
        c = uc1.p(16);
        d = uc1.o(0.5d);
        aa0 aa0Var2 = e32.b;
        e = aa0Var2;
        f = zb0Var;
        g = uc1.o(20.0d);
        h = uc1.p(14);
        i = uc1.o(0.2d);
        j = aa0Var2;
        k = zb0Var;
        l = uc1.o(16.0d);
        m = uc1.p(12);
        n = uc1.o(0.4d);
        o = aa0Var2;
        p = zb0Var;
        q = uc1.o(64.0d);
        r = uc1.p(57);
        long jO = uc1.o(0.2d);
        h02[] h02VarArr = g02.b;
        long j2 = jO & 1095216660480L;
        if (j2 == 0) {
            pg0.a("Cannot perform operation for Unspecified type.");
        }
        s = uc1.y(-g02.c(jO), j2);
        t = aa0Var2;
        u = zb0Var;
        v = uc1.o(52.0d);
        w = uc1.p(45);
        x = uc1.o(0.0d);
        y = aa0Var2;
        z = zb0Var;
        A = uc1.o(44.0d);
        B = uc1.p(36);
        C = uc1.o(0.0d);
        D = aa0Var2;
        E = zb0Var;
        F = uc1.o(40.0d);
        G = uc1.p(32);
        H = uc1.o(0.0d);
        I = aa0Var2;
        J = zb0Var;
        K = uc1.o(36.0d);
        L = uc1.p(28);
        M = uc1.o(0.0d);
        N = aa0Var2;
        O = zb0Var;
        P = uc1.o(32.0d);
        Q = uc1.p(24);
        R = uc1.o(0.0d);
        S = aa0Var2;
        T = zb0Var;
        U = uc1.o(20.0d);
        V = uc1.p(14);
        W = uc1.o(0.1d);
        aa0 aa0Var3 = e32.a;
        X = aa0Var3;
        Y = zb0Var;
        Z = uc1.o(16.0d);
        a0 = uc1.p(12);
        b0 = uc1.o(0.5d);
        c0 = aa0Var3;
        d0 = zb0Var;
        e0 = uc1.o(16.0d);
        f0 = uc1.p(11);
        g0 = uc1.o(0.5d);
        h0 = aa0Var3;
        i0 = zb0Var;
        j0 = uc1.o(28.0d);
        k0 = uc1.p(22);
        l0 = uc1.o(0.0d);
        m0 = aa0Var2;
        n0 = zb0Var;
        o0 = uc1.o(24.0d);
        p0 = uc1.p(16);
        q0 = uc1.o(0.2d);
        r0 = aa0Var3;
        s0 = zb0Var;
        t0 = uc1.o(20.0d);
        u0 = uc1.p(14);
        v0 = uc1.o(0.1d);
        w0 = aa0Var3;
        uc1.o(24.0d);
        uc1.p(16);
        uc1.o(0.15d);
        uc1.o(20.0d);
        uc1.p(14);
        uc1.o(0.25d);
        uc1.o(16.0d);
        uc1.p(12);
        uc1.o(0.4d);
        uc1.o(64.0d);
        uc1.p(57);
        uc1.p(0);
        uc1.o(52.0d);
        uc1.p(45);
        uc1.p(0);
        uc1.o(44.0d);
        uc1.p(36);
        uc1.p(0);
        uc1.o(40.0d);
        uc1.p(32);
        uc1.p(0);
        uc1.o(36.0d);
        uc1.p(28);
        uc1.p(0);
        uc1.o(32.0d);
        uc1.p(24);
        uc1.p(0);
        uc1.o(20.0d);
        uc1.p(14);
        uc1.o(0.1d);
        uc1.o(16.0d);
        uc1.p(12);
        uc1.o(0.5d);
        uc1.o(16.0d);
        uc1.p(11);
        uc1.o(0.5d);
        uc1.o(28.0d);
        uc1.p(22);
        uc1.p(0);
        uc1.o(24.0d);
        uc1.p(16);
        uc1.o(0.15d);
        uc1.o(20.0d);
        uc1.p(14);
        uc1.o(0.1d);
    }
}
