package defpackage;

/* JADX INFO: compiled from: r8-map-id-7d02091066cdaef854dd62631b7ece0560bf3f98008d2b2dd5cfb5f5ba2a990d */
/* JADX INFO: loaded from: classes.dex */
public abstract class yl {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = k41.p;
        a = j2;
        b = k41.d;
        c = k41.e;
        d = k41.n;
        long j3 = k41.y;
        e = j3;
        f = k41.i;
        long j4 = k41.g;
        g = j4;
        h = k41.b;
        i = k41.a;
        j = k41.v;
        long j5 = k41.u;
        k = j5;
        l = j5;
        m = k41.w;
        n = k41.B;
        long j6 = k41.A;
        o = j6;
        p = j6;
        q = k41.C;
        r = j4;
        s = k41.q;
        t = k41.H;
        long j7 = k41.G;
        u = j7;
        v = j7;
        w = k41.I;
        x = k41.r;
        y = k41.s;
        z = k41.x;
        long j8 = k41.z;
        A = j8;
        B = j8;
        C = j3;
        D = k41.f;
        E = k41.D;
        long j9 = k41.F;
        F = j9;
        G = j9;
        H = k41.E;
        I = j2;
        J = j2;
        K = k41.m;
        L = k41.l;
        M = k41.k;
        N = k41.o;
        O = k41.h;
        P = k41.j;
        Q = k41.t;
        R = k41.J;
        long j10 = k41.L;
        S = j10;
        T = j10;
        U = k41.K;
    }
}
