// Real, documented Zygisk entry point (zygisk_module_entry, generated by
// REGISTER_ZYGISK_MODULE below). The original .so did NOT export this
// symbol - it only exported JNI_OnLoad with the magic-number gate seen in
// jni_bridge.cpp - which means it was almost certainly `dlopen()`-ed and
// manually invoked by a separate, smaller loader module rather than being
// loaded by Zygisk directly. Since the goal here is a project that actually
// builds and loads as a Magisk/Zygisk module, this file wires the same
// reconstructed logic into the official API instead of guessing at the
// missing loader stub.

#include <sys/types.h>
#include <sys/sysmacros.h>

#include "zygisk.hpp"
#include "zygisk_entry.h"
#include "anti_detect.h"
#include "config.h"
#include "overlay.h"
#include "obfuscate.h"

#include <EGL/egl.h>
#include <android/log.h>
#include <cstdio>
#include <cstring>

#define LOG_TAG "zygisk_module"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)

namespace {

OBF_DECL(k_libegl, "libEGL.so", 0x27d4eb2fu, 0x13);

bool find_lib_dev_inode(const char* name, dev_t* dev, ino_t* inode) {
    FILE* f = fopen("/proc/self/maps", "r");
    if (!f) return false;

    char line[512];
    bool found = false;
    while (fgets(line, sizeof(line), f)) {
        if (!strstr(line, name)) continue;
        unsigned int maj = 0, min = 0;
        unsigned long ino = 0;
        if (sscanf(line, "%*x-%*x %*4s %*x %x:%x %lu", &maj, &min, &ino) == 3) {
            *dev = makedev(maj, min);
            *inode = static_cast<ino_t>(ino);
            found = true;
            break;
        }
    }
    fclose(f);
    return found;
}

using eglSwapBuffers_t = EGLBoolean (*)(EGLDisplay, EGLSurface);
eglSwapBuffers_t orig_eglSwapBuffers = nullptr;

EGLBoolean hooked_eglSwapBuffers(EGLDisplay dpy, EGLSurface surf) {
    overlay::render_frame();
    return orig_eglSwapBuffers(dpy, surf);
}

} // namespace

class ReversedZygiskModule : public zygisk::ModuleBase {
public:
    void onLoad(zygisk::Api* api, JNIEnv* env) override {
        this->api = api;
        this->env = env;
    }

    void postAppSpecialize(const zygisk::AppSpecializeArgs*) override {
        // Background: log entry + resolve libunity.so's base address.
        // Matches the payload thread reconstructed in zygisk_entry.cpp.
        zentry::start_thread();

        // Synchronous gate: pltHookRegister/pltHookCommit are only valid
        // for the duration of this call, so the activation decision has to
        // happen here rather than off of the background thread.
        if (anti_detect::analysis_tools_present()) {
            LOGD("analysis tooling detected, staying dormant");
            return;
        }
        if (!config::load_and_validate()) {
            LOGD("local config missing/invalid, staying dormant");
            return;
        }

        overlay::init();

        dev_t dev; ino_t ino;
        const char* libegl = OBF_STR(k_libegl);
        if (find_lib_dev_inode(libegl, &dev, &ino)) {
            api->pltHookRegister(dev, ino, "eglSwapBuffers",
                                  reinterpret_cast<void*>(hooked_eglSwapBuffers),
                                  reinterpret_cast<void**>(&orig_eglSwapBuffers));
            api->pltHookCommit();
        } else {
            LOGD("libEGL.so not found in maps, overlay hook skipped");
        }
    }

private:
    zygisk::Api* api = nullptr;
    JNIEnv* env = nullptr;
};

REGISTER_ZYGISK_MODULE(ReversedZygiskModule)
